-- ~/.hammerspoon/keybinds_apps.lua
-- App focus or launch keybindings using hyper key (Caps Lock mapped to F19)

bindApp({}, 'B', "Firefox")
bindApp({}, '1', "1Password")
bindApp({}, 'C', "Calendar")
bindApp({}, 'A', "Claude")
bindApp({}, 'T', "iTerm")
bindApp({}, 'E', "Mail")
bindApp({}, 'O', "Obsidian")
bindApp({}, 'P', "Podcasts")
bindApp({}, 'R', "Reminders")
bindApp({}, 'S', "Slack")
bindApp({}, 'W', "WhatsApp")
bindApp({}, 'Z', "Zotero")
bindApp({}, 'N', "Notes")

bindApp({'shift'}, 'B', "Firefox")
bindApp({'shift'}, 'F', "FileZilla")
bindApp({'shift'}, 'T', "Music")
bindApp({'shift'}, 'C', "Visual Studio Code")
bindApp({'shift'}, 'W', "Microsoft Word")
bindApp({'shift'}, 'E', "Microsoft Excel")
bindApp({'shift'}, 'P', "Microsoft PowerPoint")
bindApp({'shift'}, 'O', "Protégé")
bindApp({'shift'}, 'A', "Google Gemini")
bindApp({'shift'}, 'Z', "zoom.us")
